name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # clang
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.4.1
      with:
        source: src
    # test
    - name: action-gtest
      uses: CyberZHG/github-action-gtest@0.0.1
      with:
        args: -e src/unittests/unittests
