name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        build_type:
          - Debug
        os:
          - ubuntu-latest
        toolchain:
          - linux_clang
        # - linux_clang_asan
        # - linux_clang_benchmark
        # - linux_clang_lsan
        # - linux_clang_msan
        # - linux_clang_tsan
        # - linux_clang_ubsan
          - linux_gcc
        include:
          - os: macos-latest
            toolchain: macos_clang
          - os: windows-latest
            toolchain: windows_msvc
        # - os: ubuntu-latest
        #   toolchain: linux_clang_benchmark
        #   build_type: Release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

    # - name: Boot
    #   run: boot.sh

      - name: Configure (${{ matrix.build_type }}) with (${{ matrix.toolchain }})
        run: cmake -S . -B .build -DCMAKE_TOOLCHAIN_FILE="toolchain/${{ matrix.toolchain }}.cmake" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build .build --parallel 8

      - name: Test
        run: (cd .build && ctest --extra-verbose)
