name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    # clang
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.4.1
      with:
        source: src
    # tidy
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
