name: main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - ubuntu_llvm
        #  - linux_llvm_asan
        #  - linux_llvm_lsan
        #  - linux_llvm_msan
        #  - linux_llvm_tsan
        #  - linux_llvm_ubsan
          - ubuntu_gcc
        build_type:
          - Debug
        include:
          - os: macos-latest
            toolchain: macos_llvm
            build_type: Debug
          - os: windows-latest
            toolchain: windows_msvc
            build_type: Debug
          - os: ubuntu-latest
            toolchain: ubuntu_llvm
            build_type: Release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      # Special step for ubuntu-latest.
      - name: Bootstrap toolchain ${{ matrix.toolchain }}
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo python .github/workflows/bootstrap.py ${{ matrix.toolchain }}

      - name: Configure ${{ matrix.build_type }}
        run: cmake -S . -B .build -DCMAKE_TOOLCHAIN_FILE="toolchain/${{ matrix.toolchain }}.cmake" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build .build --parallel 8

      - name: Test
        run: (cd .build && ctest --extra-verbose)
