name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # clang-format
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.4.1
      with:
        source: src
    # test
    - name: submodule init
      run: git submodule update --init --recursive
    - name: bootstrap
      run: ./bootstrap.sh
    - name: install gtest # just fix Ci
      run: sudo bash install_deps.sh
    - name: build
      run: ./build.sh
    - name: test
      run: ./build/src/unittests/unittests
