# Options

set(CPP_PROJECT_TEMPALTE_BENCHMARKS
    ON
    CACHE BOOL "" FORCE)

set(CPP_PROJECT_TEMPALTE_EXAMPLES
    ON
    CACHE BOOL "" FORCE)

set(CPP_PROJECT_TEMPALTE_TESTS
    ON
    CACHE BOOL "" FORCE)
