list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
include(ubuntu_llvm)

# LSAN flags, https://clang.llvm.org/docs/LeakSanitizer.html#usage

# * -fsanitize=leak enables LSAN.
set(CPP_PROJECT_TEMPLATE_LSAN_FLAGS "-fsanitize=leak")

set(CMAKE_C_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
