list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/toolchain")
include(ubuntu_llvm)

# LSAN flags:
# Reference https://clang.llvm.org/docs/LeakSanitizer.html#id2
# -fsanitize=leak enables LSAN.
set(CPP_PROJECT_TEMPLATE_LSAN_FLAGS "-fsanitize=leak")

set(CMAKE_C_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_LSAN_FLAGS}")
