list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
include(ubuntu_llvm)

# TSAN flags, https://clang.llvm.org/docs/ThreadSanitizer.html#usage

# * -fsanitize=thread enables TSAN.

set(CPP_PROJECT_TEMPLATE_TSAN_FLAGS "-fsanitize=thread")

set(CMAKE_C_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_TSAN_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_TSAN_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_TSAN_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_TSAN_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CPP_PROJECT_TEMPLATE_TSAN_FLAGS}")
